/// احتياطي عند عدم توفر قالب من لوحة التحكم (قبل أول مزامنة).
const Map<String, dynamic> kFallbackReceiptPrintTemplate = {
  'version': 2,
  'paperMm': 80,
  'footerBlankLines': 1,
  'branding': {
    'showLogo': true,
    'logoUrl': '',
    'logoWidth': 200,
    'legalName': 'شركة التوزيع',
    'legalNameFont': 32,
    'companyName': 'Edari',
    'companyFont': 17,
    'title': 'وصل قبض',
    'titleFont': 26,
    'footer': 'شكراً لتعاملكم — نتشرف بخدمتكم',
    'footerFont': 17,
  },
  'typography': {
    'bodyFont': 18,
    'labelFont': 16,
    'amountFont': 36,
    'legalFont': 17,
  },
  'content': {
    'showLegalName': true,
    'showCompany': true,
    'showTitle': true,
    'showDeliveryNo': true,
    'showDate': true,
    'showAgent': true,
    'showCustomer': true,
    'showCustomerNum': true,
    'showTree': false,
    'showNotes': true,
    'legalText': 'وصلني منكم المبلغ المذكور أعلاه نقداً',
    'dividerStyle': 'light',
  },
};
